name: Release Obsidian plugin

on:
    release:
        types: [published]  # 网页点击 "Publish release" 时触发

permissions:
    contents: write

env:
    PLUGIN_ID: yearly-glance

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.release.tag_name }}  # 检出标签对应的代码
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Prepare manifest
              run: |
                  if [[ ${{ github.event.release.tag_name }} == *"beta"* ]]; then
                    cp manifest-beta.json manifest.json
                  fi

            - name: Build
              run: |
                  npm install -g yarn
                  yarn
                  yarn run build --if-present
                  mkdir ${{ env.PLUGIN_ID }}
                  cp main.js manifest.json styles.css ${{ env.PLUGIN_ID }}
                  zip -r ${{ env.PLUGIN_ID }}.zip ${{ env.PLUGIN_ID }}
                  ls

            - name: Upload assets to Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.event.release.tag_name }}
                  # 关键：不设置 body，保留你在网页上填写的内容
                  # 只上传文件
                  files: |
                      ${{ env.PLUGIN_ID }}.zip
                      main.js
                      manifest.json
                      styles.css
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
